var src = {
	"title": "首页",
	"url": "home.htm",
	"isChildUrl": false,
	"class": "r1",
	"childList": [{
		"title": "平台管理",
		"url": "od/admin/adminIndex.htm",
		"isChildUrl": false,
		"class": "r2",
		"childList": [{
			"title": "数据资源管理",
			"url": "od/index.htm",
			"isChildUrl": false,
			"class": "r3",
			"childList": [{
				"title": "数据资源目录",
				"url": "od/catalog/index.htm",
				"isChildUrl": true,
				"class": "r4",
				"childList": [{
					"title": "应用系统注册",
					"url": "od/admin/datasource/adddatasource.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": []
				}, {
					"title": "资源字典注册",
					"url": "od/admin/catalog/catalogDicAdd.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": []
				}, {
					"title": "数据资源注册",
					"url": "od/admin/catalog/addCatalog.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": []
				}, {
					"title": "注册资源管理",
					"url": "od/admin/catalog/catalogList.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": [{
						"title": "编辑",
						"url": "od/admin/catalog/catalogedit.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": []
					}, {
						"title": "详情",
						"url": "od/admin/catalog/detail.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": []
					}]
				}, {
					"title": "资源监测",
					"url": "od/admin/datadetect/datalogDetect.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": [{
						"title": "数据资源详情",
						"url": "od/admin/catalog/detail.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": []
					}]
				}, {
					"title": "数据资源浏览",
					"url": "od/catalog/index.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": [{
						"title": "数据资源详情",
						"url": "od/admin/catalog/detail.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": []
					}]
				}]
			}, {
				"title": "数据资源管理",
				"url": "od/admin/catalog/catalogCheck.htm",
				"isChildUrl": true,
				"class": "r4",
				"childList": [{
					"title": "数据资源审核",
					"url": "od/admin/catalog/catalogCheck.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": []
				}, {
					"title": "应用系统管理",
					"url": "od/admin/datasource/datasourcelist.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": [{
						"title": "编辑库",
						"url": "od/admin/datasource/updatedatasource.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": []
					}]
				}, {
					"title": "资源字典管理",
					"url": "od/admin/catalog/catalogDicMan.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": [{
						"title": "编辑",
						"url": "od/admin/catalog/catalogDicEdit.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": []
					}, {
						"title": "详情",
						"url": "od/admin/catalog/catalogDicDetail.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": []
					}]
				}, {
					"title": "资源分类查询",
					"url": "od/catalog/chartIndex.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": [{
						"title": "数据资源详情",
						"url": "od/catalog/detail.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": []
					}]
				}, {
					"title": "数据资源编目",
					"url": "od/admin/dataexport/sourceExport.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": []
				}, {
					"title": "服务发布",
					"url": "od/admin/service/chooseCatalog.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": []
				}]
			}, {
				"title": "数据标准",
				"url": "od/meta/dicCode.htm",
				"isChildUrl": true,
				"class": "r4",
				"childList": [{
					"title": "概览",
					"url": "od/meta/metaView.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": []
				}, {
					"title": "数据元",
					"url": "od/meta/metaCodePub.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": [{
						"title": "明细页面",
						"url": "od/meta/dicCode.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": []
					}]
				}, {
					"title": "代码字典",
					"url": "od/meta/dicCode.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": []
				}, {
					"title": "部门代码",
					"url": "od/meta/orgCode.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": []
				}, {
					"title": "标准目录",
					"url": "od/admin/catalog/dataNoTag.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": []
				}, {
					"title": "数据元治理",
					"url": "od/catalog/metaDataIndex.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": []
				}]
			}, {
				"title": "数据质量",
				"url": "od/dataquality/report.htm",
				"isChildUrl": true,
				"class": "r4",
				"childList": [{
					"title": "质量检测配置",
					"url": "od/dataquality/checkRule.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": [{
						"title": "添加",
						"url": "od/dataquality/checkRuleItem.htm?Type=Add",
						"isChildUrl": false,
						"class": "r6",
						"childList": []
					}, {
						"title": "编辑",
						"url": "od/dataquality/checkRuleItem.htm?Type=Update&id=957033",
						"isChildUrl": false,
						"class": "r6",
						"childList": []
					}]
				}, {
					"title": "检查任务",
					"url": "od/dataquality/checkReport.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": [{
						"title": "新增",
						"url": "od/dataquality/newTask.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": []
					}, {
						"title": "操作",
						"url": "od/dataquality/opTask.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": []
					}, {
						"title": "编辑",
						"url": "od/dataquality/editTask.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": []
					}]
				}, {
					"title": "检查报告",
					"url": "od/dataquality/report.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": []
				}, {
					"title": "检查报告列表",
					"url": "od/dataquality/reportList.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": []
				}]
			}, {
				"title": "资源监控",
				"url": "od/admin/datadetect/dataDetect.htm",
				"isChildUrl": false,
				"class": "r4",
				"childList": []
			}, {
				"title": "通知公告",
				"url": "od/msg/notice.htm",
				"isChildUrl": false,
				"class": "r4",
				"childList": []
			}]
		}, {
			"title": "服务资源管理",
			"url": "oam/servicelist/serviceList.htm?first_group=root_util",
			"isChildUrl": true,
			"class": "r3",
			"childList": [{
				"title": "服务资源目录",
				"url": "oam/servicelist/serviceList.htm?first_group=root_util",
				"isChildUrl": true,
				"class": "r4",
				"childList": [{
					"title": "服务目录",
					"url": "oam/servicelist/serviceList.htm?first_group=root_util",
					"isChildUrl": true,
					"class": "r5",
					"childList": [{
						"title": "云搜索服务",
						"url": "oam/servicelist/serviceList.htm?first_group=root_util",
						"isChildUrl": true,
						"isOnePage": true,
						"class": "r6",
						"childList": [{
							"title": "服务信息概览",
							"url": "oam/servicelist/serviceInfo.htm",
							"isChildUrl": true,
							"class": "r7",
							"childList": []
						}]
					}, {
						"title": "云平台服务",
						"url": "oam/servicelist/serviceList.htm?first_group=root_platform",
						"isChildUrl": true,
						"isOnePage": true,
						"class": "r6",
						"childList": [{
							"title": "服务信息概览",
							"url": "oam/servicelist/serviceInfo.htm",
							"isChildUrl": true,
							"class": "r7",
							"childList": []
						}]
					}, {
						"title": "数据比对服务",
						"url": "oam/servicelist/serviceList.htm?first_group=root_business",
						"isChildUrl": true,
						"isOnePage": true,
						"class": "r6",
						"childList": [{
							"title": "服务信息概览",
							"url": "oam/servicelist/serviceInfo.htm",
							"isChildUrl": true,
							"class": "r7",
							"childList": []
						}]
					}, {
						"title": "信息布控服务",
						"url": "oam/servicelist/serviceList.htm?first_group=root_info",
						"isChildUrl": true,
						"isOnePage": true,
						"class": "r6",
						"childList": [{
							"title": "服务详细信息",
							"isChildUrl": false,
							"url": "oam/servicelist/serviceInfo.htm",
							"class": "r7",
							"childList": []
						}]
					}, {
						"title": "数据资源服务",
						"url": "oam/servicelist/serviceList.htm?first_group=root_catalog",
						"isChildUrl": true,
						"isOnePage": true,
						"class": "r6",
						"childList": [{
							"title": "服务详细信息",
							"isChildUrl": false,
							"url": "oam/servicelist/serviceInfo.htm",
							"class": "r7",
							"childList": []
						}]
					}]
				}, {
					"title": "最新服务",
					"url": "oam/servicelist/latestServiceList.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": [{
						"title": "服务信息概览",
						"url": "oam/servicelist/serviceInfo.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": []
					}]
				}, {
					"title": "热门排行",
					"url": "oam/servicelist/hotServiceList.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": [{
						"title": "服务信息概览",
						"url": "oam/servicelist/serviceInfo.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": []
					}]
				}, {
					"title": "使用文档",
					"url": "oam/servicelist/serviceDocument.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": [{
						"title": "服务信息概览",
						"url": "oam/servicelist/serviceInfo.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": []
					}]
				}]
			}, {
				"title": "服务申请管理",
				"url": "oam/manager/applyedService.htm",
				"isChildUrl": true,
				"class": "r4",
				"childList": [{
					"title": "我的申请",
					"url": "oam/manager/applyedService.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": [{
						"title": "待审核",
						"url": "oam/manager/createdServiceAuthorize.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": [{
							"title": "服务信息概览",
							"url": "oam/servicelist/serviceInfo.htm",
							"isChildUrl": false,
							"class": "r7",
							"childList": []
						}]
					}, {
						"title": "已通过",
						"url": "oam/manager/passedServiceAuthorize.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": [{
							"title": "服务信息概览",
							"url": "oam/servicelist/serviceInfo.htm",
							"isChildUrl": false,
							"class": "r7",
							"childList": []
						}]
					}, {
						"title": "被驳回",
						"url": "oam/manager/rejectServiceAuthorize.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": [{
							"title": "服务信息概览",
							"url": "oam/servicelist/serviceInfo.htm",
							"isChildUrl": false,
							"class": "r7",
							"childList": []
						}]
					}, {
						"title": "被取消",
						"url": "oam/manager/cancelledServiceAuthorize.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": [{
							"title": "服务信息概览",
							"url": "oam/servicelist/serviceInfo.htm",
							"isChildUrl": false,
							"class": "r7",
							"childList": []
						}]
					}]
				}, {
					"title": "服务申请方",
					"url": "oam/manager/serviceApply.htm",
					"isChildUrl": true,
					"class": "r5",
					"childList": [{
						"title": "服务申请方列表",
						"url": "oam/manager/serviceApply.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": []
					}]
				}, {
					"title": "申请审核",
					"url": "oam/manager/serviceAuthorize.htm",
					"isChildUrl": true,
					"class": "r5",
					"childList": [{
						"title": "申请审核",
						"url": "oam/manager/serviceAuthorize.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": []
					}, {
						"title": "取消通过",
						"url": "oam/manager/cancelServiceAuthorize.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": []
					}]
				}]
			}, {
				"title": "服务资源注册",
				"url": "oam/manager/createService.htm",
				"isChildUrl": true,
				"class": "r4",
				"childList": [{
					"title": "服务资源注册",
					"url": "oam/manager/createService.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": []
				}, {
					"title": "注册服务管理",
					"url": "oam/manager/releasedService.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": [{
						"title": "服务编辑",
						"url": "oam/manager/editService.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": []
					}]
				}]
			}, {
				"title": "服务资源管理",
				"url": "oam/manager/serviceAudit.htm",
				"isChildUrl": true,
				"class": "r4",
				"childList": [{
					"title": "服务上线审核",
					"url": "oam/manager/serviceAudit.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": [{
						"title": "服务信息概览",
						"url": "oam/servicelist/serviceInfo.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": []
					}]
				}, {
					"title": "分组管理",
					"url": "oam/manager/groupMan.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": []
				}, {
					"title": "级别管理",
					"url": "oam/manager/serviceLevel.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": []
				}, {
					"title": "字典管理",
					"url": "oam/manager/pubDictInfo.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": []
				}, {
					"title": "资源编目",
					"url": "oam/manager/zybm.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": []
				}, {
					"title": "应用授权展示",
					"url": "oam/servicelist/showUnitService.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": []
				}]
			}, {
				"title": "服务总线监控",
				"url": "oam/manager/monitorList.htm",
				"isChildUrl": true,
				"class": "r4",
				"childList": [{
					"title": "监控列表",
					"url": "oam/manager/monitorList.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": [{
						"title": "监控详情",
						"url": "oam/manager/monitorDetail.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": []
					}]
				}, {
					"title": "创建监控",
					"url": "oam/monitor/createMonitor.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": []
				}, {
					"title": "监控统计",
					"url": "oam/monitor/monitorStatistics.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": []
				}]
			}, {
				"title": "服务总线统计",
				"url": "oam/statics/serviceAnalysis.htm",
				"isChildUrl": true,
				"class": "r4",
				"childList": [{
					"title": "排行统计",
					"url": "oam/statics/serviceAnalysis.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": []
				}, {
					"title": "月度统计",
					"url": "oam/statics/serviceStatics.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": [{
						"title": "服务信息概览",
						"url": "oam/servicelist/serviceInfo.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": []
					}]
				}, {
					"title": "服务调用",
					"url": "oam/statics/serviceUsage.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": []
				}, {
					"title": "服务响应时间",
					"url": "oam/manager/serviceRespTime.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": []
				}, {
					"title": "调用成功率",
					"url": "oam/statics/serviceSucRate.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": []
				}]
			}]
		}, {
			"title": "应用资源管理",
			"url": "acweb/index.htm",
			"isChildUrl": true,
			"class": "r3",
			"childList": [{
				"title": "首页",
				"url": "acweb/index.htm",
				"isChildUrl": false,
				"class": "r4",
				"childList": [{
					"title": "详细",
					"url": "acweb/store/detail.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": []
				}]
			}, {
				"title": "分组浏览",
				"url": "acweb/store/search.htm",
				"isChildUrl": false,
				"class": "r4",
				"childList": [{
					"title": "详细",
					"url": "acweb/store/detail.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": []
				}]
			}, {
				"title": "全部应用",
				"url": "acweb/open/appList.htm",
				"isChildUrl": false,
				"class": "r4",
				"childList": [{
					"title": "创建应用",
					"url": "acweb/open/appCreate.htm",
					"isChildUrl": false,
					"class": "r5",
					"childList": []
				}, {
					"title": "应用信息",
					"url": "acweb/open/app.htm",
					"isChildUrl": true,
					"class": "r5",
					"childList": [{
						"title": "基本信息",
						"url": "acweb/open/app.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": []
					}, {
						"title": "桌面应用",
						"url": "acweb/open/app.htm?app_id=5335&route=pc&app_type=pc",
						"isChildUrl": false,
						"class": "r6",
						"childList": []
					}, {
						"title": "移动应用",
						"url": "acweb/open/app.htm?app_id=5335&route=mobile&app_type=mobile",
						"isChildUrl": false,
						"class": "r6",
						"childList": []
					}, {
						"title": "站外应用",
						"url": "acweb/open/app.htm?app_id=5335&route=outter&app_type=website",
						"isChildUrl": false,
						"class": "r6",
						"childList": []
					}]
				}]
			}, {
				"title": "应用管理",
				"url": "acweb/manager/unAuditedApps.htm",
				"isChildUrl": true,
				"class": "r4",
				"childList": [{
					"title": "应用管理",
					"url": "acweb/manager/unAuditedApps.htm",
					"isChildUrl": true,
					"class": "r5",
					"childList": [{
						"title": "待审核列表",
						"url": "acweb/manager/unAuditedApps.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": [{
							"title": "查看详情",
							"url": "acweb/manager/approveAppView.htm",
							"isChildUrl": false,
							"class": "r7",
							"childList": []
						}]
					}, {
						"title": "已上线列表",
						"url": "acweb/manager/auditedApps.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": [{
							"title": "查看详情",
							"url": "acweb/manager/approveAppView.htm",
							"isChildUrl": false,
							"class": "r7",
							"childList": []
						}]
					}, {
						"title": "已下线列表",
						"url": "acweb/manager/offlineApps.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": [{
							"title": "查看详情",
							"url": "acweb/manager/approveAppView.htm",
							"isChildUrl": false,
							"class": "r7",
							"childList": []
						}]
					}, {
						"title": "应用推荐",
						"url": "acweb/manager/recommendApps.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": [{
							"title": "查看详情",
							"url": "acweb/manager/approveAppView.htm",
							"isChildUrl": false,
							"class": "r7",
							"childList": []
						}]
					}]
				}, {
					"title": "主题管理",
					"url": "acweb/manager/addTheme.htm",
					"isChildUrl": true,
					"class": "r5",
					"childList": [{
						"title": "创建主题",
						"url": "acweb/manager/addTheme.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": []
					}, {
						"title": "主题列表",
						"url": "acweb/manager/themeList.htm",
						"isChildUrl": false,
						"class": "r6",
						"childList": [{
							"title": "应用列表",
							"url": "acweb/manager/themeApp.htm",
							"isChildUrl": false,
							"class": "r7",
							"childList": []
						}]
					}]
				}]
			}]
		}]
	}]
}